# YOUR NAME OR TITLE OF YOUR SITE
name: YELLKO

# YOUR BRAND/PERSONAL TAGLINE
tagline: GAMER 🕹️ / STREAMER 📺 / VATER 👨‍🍼 | EGO-SHOOTER 🎯 | MMORPGS 🧚‍♀️ | HACK'N'SLAYS 🪓 | LIVE on Twitch & TikTok

# YOUR/BRAND IMAGE URL
Image_URL: https://yt3.ggpht.com/CSl-xq-dytN_IWcwvGhRGiIDLfqg6mj-g74MbQUdrDO2wZaaYdc1uGvloZ7KKuC8-VmYQ5zi=s600-c-k-c0x00ffffff-no-rj-rp-mo

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://yt3.ggpht.com/CSl-xq-dytN_IWcwvGhRGiIDLfqg6mj-g74MbQUdrDO2wZaaYdc1uGvloZ7KKuC8-VmYQ5zi=s600-c-k-c0x00ffffff-no-rj-rp-mo

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # FACEBOOK
  - Name: Facebook
    URL: 
    Username: yellkoo
    Color: '#3b5998'
    Icon-Class: fab fa-facebook
  
    # TWITCH
  - Name: TWITCH
    URL: 'https://twitch.tv'
    Username: yellko
    Icon-Class: fab fa-twitch
    Color: '#9147fe'
    Text_Color: '#ffffff'
    
    # TIKTOK
  - Name: TIKTOK
    URL: https://www.tiktok.com
    Username: '@yell.ko'
    Color: '#000000'
    Icon-Class: fab fa-tiktok
     
    # THREADS
  - Name: THREADS
    URL: https://www.threads.net/
    Username: yellkoo
    Color: '#000000'
    Icon-Class: fa-solid fa-at
    Text_Color: '#ffffff'
 
     # Bluesky
  - Name: BLUESKY
    URL: https://bsky.app/profile/
    Username: yellko.bsky.social
    Color: '#3496fe'
    Icon-Class: fa-solid fa-at
    Text_Color: '#ffffff'

    # X
  - Name: X
    URL: 
    Username: yellkoo
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter

    # YOUTUBE
  - Name: YOUTUBE
    URL: https://www.youtube.com/channel
    Username: UCLiNrhQNsjfdKGGMI7rfjzw
    Color: '#ff0000'
    Icon-Class: fab fa-youtube
    
    # INSTAGRAM
  - Name: INSTAGRAM
    URL: https://www.instagram.com
    Username: yellkoo
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram
    
    # KO-FI
  - Name: KO.FFEE
    URL: https://ko-fi.com
    Username: yellko
    Color: '#ffb142'
    Icon-Class: fas fa-link
   
    # TESLA
  - Name: TESLA
    URL: https://www.tesla.com/de_DE/referral
    Username: kevin117149
    Color: '#ff0000'
    Icon-Class: fas fa-link

    # CLUBHOUSE
  - Name: Clubhouse
    URL: 
    Username: '@yellkoo'
    Color: '#f1c40f'
    Icon-Class: fas fa-hand-paper -mt-0.5
    
    # LINKEDIN
  - Name: LinkedIn
    URL: 
    Username: yellkoo
    Color: '#2867B2'
    Icon-Class: fab fa-linkedin-in

    # GITHUB
  - Name: GitHub
    URL: 
    Username: yellkoo
    Color: '#6e5494'
    Icon-Class: fab fa-github

    # WordPress
  - Name: WordPress.org
    URL: 
    Username: yellkoo
    Icon-Class: fa-brands fa-wordpress-simple
    Color: '#0073AA'
    Text_Color: '#ffffff'

    # EMAIL
  - Name: Email
    URL: 
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'

  #   # Drupal
  # - Name: Drupal
  #   URL: 'https://www.drupal.org/u'
  #   Username: yellko
  #   Icon-Class: fa-brands fa-drupal
  #   Color: '#0077C0'
  #   Text_Color: '#ffffff'

    # VIMEO
  - Name: Vimeo
    URL: 
    Username: yellko
    Icon-Class: fab fa-vimeo-v
    Color: '#1ab7ea'
    Text_Color: '#ffffff'

    # MESSENGER
  - Name: Messenger
    URL: 
    Username: yellko
    Color: '#006AFF'
    Icon-Class: fab fa-facebook-messenger

    # Cal.com
  - Name: Cal.com
    URL: 
    Username: yellko
    Color: '#888888'
    Icon-Class: fa fa-calendar-check
    Text_Color: '#ffffff'

    # REDDIT
  - Name: Reddit
    URL: 
    Username: yellko
    Color: '#FF4500'
    Icon-Class: fab fa-reddit-alien

  #   # WHATSAPP
  # - Name: WhatsApp
  #   URL: https://wa.me
  #   Username: '+1123456789'
  #   Color: '#25d366'
  #   Icon-Class: fab fa-whatsapp

    # TELEGRAM
  - Name: Telegram
    URL: 
    Username: yellko
    Color: '#0088cc'
    Icon-Class: fab fa-telegram-plane

    # SNAPCHAT
  - Name: Snapchat
    URL: 
    Username: 'yellkoo'
    Color: '#FFFC00'
    Text_Color: '#000000'
    Icon-Class: fab fa-snapchat-ghost

    # STEAM
  - Name: Steam
    URL: 
    Username: 'yellko'
    Color: '#66c0f4'
    Text_Color: '#000000'
    Icon-Class: fab fa-steam

  #   # DISCORD
  # - Name: Discord
  #   URL: 'https://discord.gg'
  #   Username: 
  #   Icon-Class: fab fa-discord
  #   Color: '#5865F2'
  #   Text_Color: '#ffffff'

    # PINTEREST
  - Name: Pinterest
    URL: 
    Username: 'yellkoo'
    Color: '#E60023'
    Icon-Class: fab fa-pinterest

    # BEHANCE
  - Name: Behance
    URL: 
    Username: yellkoo
    Color: '#1769ff'
    Icon-Class: fab fa-behance

  #   # DRIBBBLE
  # - Name: Dribbble
  #   URL: https://dribbble.com
  #   Username: 
  #   Color: '#ea4c89'
  #   Icon-Class: fab fa-dribbble

    # DEVIANTART
  - Name: DeviantArt
    URL: 
    Username: yellko
    Icon-Class: fab fa-deviantart
    Color: '#05CC46'
    Text_Color: '#ffffff'

    # FIGMA
  - Name: Figma
    URL: 
    Username: '@yellko'
    Icon-Class: fab fa-figma
    Color: '#ff2865'
    Text_Color: '#ffffff'

    # SPOTIFY
  - Name: Spotify
    URL: 
    Username: 
    Color: '#1DB954'
    Icon-Class: fab fa-spotify

    # SOUNDCLOUD
  - Name: SoundCloud
    URL: 
    Username: yellkoo
    Color: '#FE5000'
    Icon-Class: fab fa-soundcloud

  - Name: Skype
    URL: 
    Icon-Class: fa-brands fa-skype
    Color: '#00aff0'
    Text_Color: '#ffffff'

    # MEDIUM
  - Name: Medium
    URL: 
    Username: '@yellkoo'
    Icon-Class: fab fa-medium-m
    Color: '#00ab6c'
    Text_Color: '#ffffff'

    # DEV.TO
  - Name: Dev.to
    URL: 
    Username: yellkoo
    Icon-Class: fab fa-dev
    Color: '#ffffff'
    Text_Color: '#000000'

  #   # TUMBLR
  # - Name: Tumblr
  #   URL: https://www.tumblr.com
  #   Username: 
  #   Color: '#35465c'
  #   Icon-Class: fab fa-tumblr

  # BUY ME A COFFEE
  - Name: BuyMeACoffee
    URL: 
    Username: yellko
    Icon-Class: fas fa-mug-hot
    Color: '#FFDD00'
    Text_Color: '#000000'

    # CUSTOM LINK
  - Name: BLOG
    URL: https://yellko.github.io/
    Icon-Class: fas fa-link
    Color: '#6E695B'
    Text_Color: '#ffffff'

  - Name: Links
    URL: 
    Icon-Class: fas fa-link
    Color: '#d94869'
    Text_Color: '#ffffff'

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: ''

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
